feature_extract_enable : 0
point_filter_num : 300
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.2
filter_size_map : 0.1
cube_side_length : 20
debug : 0
grid_size : 80
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
cam_fx: 608.327
cam_fy: 608.308
cam_cx: 639.605
cam_cy: 366.594

common:
    lid_topic:  "/points2"
    imu_topic:  "/imu"

preprocess:
    lidar_type: 4 # Livox Avia LiDAR
    scan_line: 64
    blind: 0.1 # blind x m disable

mapping:
    acc_cov_scale: 100000
    gyr_cov_scale: 100000
    fov_degree:    90
    extrinsic_T: [ -0.047, 0.0285, 0.0033]
    extrinsic_R: [ -0.00061492, 0.00730016, -0.999973, 
                   -0.999996, -0.00270155, 0.000595212, 
                   -0.00269713, 0.99997, 0.00730179]

camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: /rgb/image_raw
    #xiyuan
    Rcl: [1.0,0.0,0.0,
          0.0,1.0,0.0,
          0.0,0.0,1.0]
    Pcl: [0.0, 0.0, 0.0]
    
