feature_extract_enable : 0
point_filter_num : 3
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.08
filter_size_map : 0.08
cube_side_length : 20
debug : 0
grid_size : 80
patch_size : 8
img_enable : 1
lidar_enable : 0
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 1000 # 1000
laser_point_cov : 0.001 # 0.001
cam_fx: 608.327
cam_fy: 608.308
cam_cx: 639.605
cam_cy: 366.594

common:
    lid_topic:  "/points2"
    imu_topic:  "/imu"

preprocess:
    lidar_type: 4 # Livox Avia LiDAR
    scan_line: 64
    blind: 0.1 # blind x m disable

mapping:
    acc_cov_scale: 100000
    gyr_cov_scale: 100000
    fov_degree:    90
    extrinsic_T: [ -0.0505226, 0.00383, 0.00159]
    extrinsic_R: [ -0.00455602, 0.108595, -0.99407, 
                   -0.999958, -0.00837415, 0.00366818, 
                   -0.0079262, 0.994051, 0.108628]

camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: /rgb/image_raw
    #xiyuan
    Rcl: [0.999946, 0.0102355, 0.00196952,
        -0.0103861, 0.994365,  0.105501,
          -0.000878569, -0.105515, 0.9944]
    Pcl: [-0.0319896, -0.001733, 0.0040324]
    
