feature_extract_enable : 0
point_filter_num : 50
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.2
filter_size_map : 0.1
cube_side_length : 20
debug : 0
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100000000 # 1000
laser_point_cov : 0.001 # 0.001
cam_fx: 594.196
cam_fy: 595.270
cam_cx: 330.275
cam_cy: 266.435

common:
    lid_topic:  "/camera/depth/color/points"
    imu_topic:  "/camera/imu"

preprocess:
    lidar_type: 4 # Livox Avia LiDAR
    scan_line: 64
    blind: 0.1 # blind x m disable

mapping:
    acc_cov_scale: 10000
    gyr_cov_scale: 10000
    fov_degree:    90
    extrinsic_T: [ 0.0, 0.0, 0.0 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: /camera/color/image_raw
    #xiyuan
    Rcl: [1.0,0.0,0.0,
          0.0,1.0,0.0,
          0.0,0.0,1.0]
    Pcl: [0.0, 0.0, 0.0]
    
